name: grevia
description: "Grevia — Complete Realtime Social Messaging Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State Management
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Firebase Suite
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.2

  # Realtime WebRTC Calling
  flutter_webrtc: ^1.6.2+hotfix.1

  # Local Persistence & Utilities
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3

  # QR Code Profile & Scanner
  qr_flutter: ^4.1.0

  # Media & Permissions
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5

  # UI & Visuals
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
